--- #YAML:1.0
name: Compress::ZLib
version: 2.000
author:
  - Paul Marquess <pmqs@cpan.org>
abstract: |-
  Interface to zlib compression library
license: perl
requires: 
  perl: 5.004
recommends: {}
build_requires: 
  Test::More: 0
conflicts: {}
provides:
  Compress::Zlib:
    file: lib/Compress::Zlib.pm
    version: 2.000
  Compress::Zlib:Inflate
    file: lib/Compress::Zlib.pm
    version: 2.000
  Compress::Zlib:Deflate
    file: lib/Compress::Zlib.pm
    version: 2.000
