--- #YAML:1.0
name:                Compress-Zlib
version:             2.005
abstract:            Interface to zlib compression library
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.33
distribution_type:   module
requires:     
    Compress::Raw::Zlib:           2.005
    IO::Compress::Base:            2.005
    IO::Compress::Base::Common:    2.005
    IO::Compress::Gzip:            2.005
    IO::Compress::Gzip::Constants: 2.005
    IO::Uncompress::Base:          2.005
    IO::Uncompress::Gunzip:        2.005
    Scalar::Util:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Marquess <pmqs@cpan.org>
