#!/usr/local/bin/perl

use Compress::Zlib ;

die "Usage: gzcat file...\n"
    unless @ARGV ;

foreach $file (@ARGV) {
    $gz = gzopen($file, "rb") 
         or die "Cannot open $file: $gzerrno\n" ;

    print $buffer while $gz->gzread($buffer) > 0 ;

    die "Error reading from $file: $gzerrno\n" if $gzerrno ;
    
    $gz->gzclose() ;
}
